name: Manifest Download

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:
    inputs:
      account-concurrency:
        description: 'Account concurrency'
        required: true
        default: 32
        type: number

      manifest-concurrency:
        description: 'Manifest concurrency'
        required: true
        default: 8
        type: number

concurrency:
  group: download

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Restore serverlist
        uses: actions/cache/restore@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-
          restore-keys: ${{ runner.os }}-servers-

      - name: Download manifest
        run: dotnet run --configuration Release -- download -t ${{ secrets.GITHUB_TOKEN }} -c ${{ github.event.inputs.account-concurrency || 32 }} -p ${{ github.event.inputs.manifest-concurrency || 8 }}

      - name: Save serverlist
        uses: actions/cache/save@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-${{ hashFiles('servers.bin') }}
