name: Dynamic Account Merge

on:
  issue_comment:
    types: [ created ]

jobs:
  generate-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-list.outputs.list }}
      total: ${{ steps.generate-list.outputs.total }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Generate list and set as output
        id: generate-list
        run: |
          JSON_DATA='${{ github.event.comment.body }}'
          NUM_KEYS=$(echo $JSON_DATA | jq 'keys | length')
          MAX_KEYS=$((NUM_KEYS>256?256:NUM_KEYS))
          LIST=$(seq 0 $((MAX_KEYS-1)) | jq -Rsc 'split("\n")[:-1]')
          echo "list=$LIST" >> $GITHUB_OUTPUT
          echo "total=$MAX_KEYS" >> $GITHUB_OUTPUT

  validate-account:
    needs: generate-list
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        index: ${{fromJson(needs.generate-list.outputs.matrix)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Restore serverlist
        uses: actions/cache/restore@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-
          restore-keys: ${{ runner.os }}-servers-

      - name: Save comment to file
        run: printf ${{ toJson(github.event.comment.body) }} > comment.txt

      - name: Validate account
        run: dotnet run --configuration Release -- account -a comment.txt -t ${{ secrets.GITHUB_TOKEN }} -i ${{ matrix.index }} -n ${{ needs.generate-list.outputs.total }} -k ${{ secrets.AES_KEY }}

      - name: Save serverlist
        uses: actions/cache/save@v4
        with:
          path: servers.bin
          key: ${{ runner.os }}-servers-${{ hashFiles('servers.bin') }}

